### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by nikodemadamski**
I have created Initial prototype logo For our Data Polish using DALL-E, this is only a placeholder for the final logo which will be launched next week.

### CODE REVIEW

**Review by SeanMcCrossanTUD — APPROVED** [review]
I think its a decent start for ideas but concerned with the name at the bottom. Suchs as POPTONG haha.

Think when we have the name decided it will gives us a better idea...

**Comment by SeanMcCrossanTUD** [comment]
Testing whether this works from my slack?

**Comment by SeanMcCrossanTUD** [comment]
It does, cool

**Review by D22124491-NaveenMaheswaran — APPROVED** [review]
LG, using AI to generate logo nice thinking @nikodemadamski

**Pull request merged**
