### PR TITLE
FAB-247: Made change to time of sleep

### PR DESCRIPTION
**Pull request by SeanMcCrossanTUD**
- Data prep
- Data profile

### CODE REVIEW

**Review by OluwatobiOmole — APPROVED** [review]
Standard changes to timer nothing more to evaluate Lookg good

**Review by D22124491-NaveenMaheswaran — CHANGES_REQUESTED** [review]
Its millisecond right you can increase like 10*1000 that is 10000 millisecond or 10 second

**Review by UmamaSumlinTasnuva — APPROVED** [review]
good that you made the changes requested by Naveen

**Review by D22124491-NaveenMaheswaran — APPROVED** [review]
LG

**Pull request merged**
