### PR TITLE
Fab 278 bubble chart

### PR DESCRIPTION
**Pull request by nikodemadamski**
Added
- bubble chart initial and then updated it by adding motion and colours
- changed the colours and font of the data quality metric to be correlated to its number  ( traffic lights )
- created an Excel including titles of all charts and tooltip to be implemented as h2 title and tooltip hover in the future
- (I am now working on other things, such as the pie for each metric and tooltip for those, so please wait before merging :) )

### CODE REVIEW

**Review by SeanMcCrossanTUD — CHANGES_REQUESTED** [review]
Few changes needed

- We need a filter so that the user can select between different text fields.
- Can you create a template json file, look at the example ones in assets. an element with the value in the field and the number of times that value pops up.
- It wont be usable without this stuff.

**Comment by nikodemadamski** [comment]
> Few changes needed
> 
> * We need a filter so that the user can select between different text fields.
> * Can you create a template json file, look at the example ones in assets. an element with the value in the field and the number of times that value pops up.
> * It wont be usable without this stuff.

yes thats why i created this for your response, how will we do it , i really wanted for us to specify the categorical features and then we just visualise it , since we cant really run python inside our graph to pick through and also i wanted to ask about your filter and how you made it , i need your lessons on how to make my own

**Comment by SeanMcCrossanTUD** [comment]
> > Few changes needed
> > 
> > * We need a filter so that the user can select between different text fields.
> > * Can you create a template json file, look at the example ones in assets. an element with the value in the field and the number of times that value pops up.
> > * It wont be usable without this stuff.
> 
> yes thats why i created this for your response, how will we do it , i really wanted for us to specify the categorical features and then we just visualise it , since we cant really run python inside our graph to pick through and also i wanted to ask about your filter and how you made it , i need your lessons on how to make my own

Make a sample JSON and put it in assets with the numbers needed. Check out the structure of the outliers json and follow it from there. I'll help with the filters.

**Review by D22124491-NaveenMaheswaran — APPROVED** [review]

**Review by D22124491-NaveenMaheswaran — APPROVED** [review]

**Review by SeanMcCrossanTUD — APPROVED** [review]
LG, need to fix data source but all good

**Pull request merged**
