### PR TITLE
FAB 259 Creating icons for our application

### PR DESCRIPTION
**Pull request by nikodemadamski**
Here are six icons we can use for our application charts. I will create icons for statistics that we can use in the future, but for right now, here are our initial icons for the D3 profiling page. :)

### CODE REVIEW

**Review by UmamaSumlinTasnuva — APPROVED** [review]
super cute and soooo colorful...loved all of these

**Comment by SeanMcCrossanTUD** [comment]
Hey man these icons are a bit much, could you google instead of using the generative AI. We just need stock images. They wont look good

**Comment by SeanMcCrossanTUD** [comment]
Maybe we should get andreas input, i really dont know what the cardinality one is supposed to be and have never seen a professional product use these type of things as icons. It should be cleaner in my opinion for the dashboard.

**Review by UmamaSumlinTasnuva — COMMENTED** [review]
Well, i liked these but I don't really disagree with @SeanMcCrossanTUD ...stock images or more simpler images will actually look more professional ..I think it's better if we get Andrea's suggestions about these

**Comment by SeanMcCrossanTUD** [comment]
> Well, i liked these but I don't really disagree with @SeanMcCrossanTUD ...stock images or more simpler images will actually look more professional ..I think it's better if we get Andrea's suggestions about these

Happy to bring these to Andrea when we demo with her on Thursday, but these icons dont really show tell the user anything. I actually think the data type one makes some sort of sense weirdly enough but it has a load of numbers around it, the rest in my opinion are just very cluttered and related to the chart it's showing....

**Review by D22124491-NaveenMaheswaran — APPROVED** [review]
we can keep it our artifacts

**Pull request merged**
